version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - sample:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_USER: myapp
      MYSQL_PASSWORD: password
    networks:
      - sampleNetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sampleNetwork

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - sampleNetwork

networks:
  sampleNetwork:
    driver: bridge

volumes:
  sample: