default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: myapp
  password: password
  host: db

development:
  <<: *default
  database: myapp

test:
  <<: *default
  database: myapp